<?php
if(!defined('ABSPATH'))exit;
class SMF_Decision_Engine{
 public static function init(){add_action('admin_menu',array(__CLASS__,'menu'),26);}
 public static function menu(){add_submenu_page('sync-meta-flow','Decision Center','Decision Center','manage_woocommerce','smf-decisions',array(__CLASS__,'page'));}
 private static function period($d){$d=absint($d);return in_array($d,array(7,30,90),true)?$d:30;}
 public static function recommendations($days=30,$model='last_touch'){$days=self::period($days);$x=SMF_Profitability::report($days,'BDT',$model);$z=$x['summary'];$a=array();$campaigns=$x['campaigns'];foreach($campaigns as $c){$name=(string)$c['campaign'];$profit=(float)$c['profit'];$margin=(float)$c['margin'];$spend=(float)$c['spend'];$roas=(float)$c['roas'];if($spend>0&&$profit<0)$a[]=array('priority'=>'HIGH','type'=>'campaign','title'=>'Stop or review '.$name,'detail'=>'Estimated contribution profit is negative ('.number_format_i18n($profit,2).' BDT).','action'=>'Reduce spend and inspect delivery/return economics.');elseif($profit>0&&$margin>=20&&$roas>=2)$a[]=array('priority'=>'HIGH','type'=>'campaign','title'=>'Scale '.$name,'detail'=>'Positive contribution profit, '.$margin.'% margin and '.$roas.'× ROAS.','action'=>'Increase budget gradually and monitor delivery quality.');elseif($spend>0&&$margin<10)$a[]=array('priority'=>'MEDIUM','type'=>'campaign','title'=>'Watch margin on '.$name,'detail'=>'Contribution margin is '.$margin.'%.','action'=>'Review COGS, fees, courier cost and returns before scaling.');}
 $courier=class_exists('SMF_Courier_Operations')?SMF_Courier_Operations::provider_intelligence($days):array();foreach($courier as $p){if(($p['health_label']??'')==='DEGRADED')$a[]=array('priority'=>'HIGH','type'=>'courier','title'=>'Review '.$p['provider'],'detail'=>'Courier health is '.$p['health_score'].'/100 with '.$p['delivery_sla_breaches'].' delivery-SLA breach(es).','action'=>'Route new dispatches to a healthier observed provider where operationally possible.');elseif(($p['financial_label']??'')==='WEAK')$a[]=array('priority'=>'MEDIUM','type'=>'courier','title'=>'Review courier economics: '.$p['provider'],'detail'=>'Financial/operational score is '.$p['financial_score'].'/100; impact is '.number_format_i18n($p['impact_value'],2).' BDT.','action'=>'Investigate returns, cancellations and SLA-breach value.');}
 $q=class_exists('SMF_Meta_CAPI')?SMF_Meta_CAPI::get_queue_stats():array();if((int)($q['failed']??0)>0)$a[]=array('priority'=>'HIGH','type'=>'system','title'=>'Resolve CAPI failures','detail'=>(int)$q['failed'].' failed event(s) remain in the queue.','action'=>'Open Diagnostics and inspect failed CAPI events before relying on conversion reporting.');if((int)($q['pending']??0)>50)$a[]=array('priority'=>'MEDIUM','type'=>'system','title'=>'CAPI queue backlog','detail'=>(int)$q['pending'].' pending event(s).','action'=>'Check WP-Cron and queue processing health.');if((float)$z['contribution_profit']<0)$a[]=array('priority'=>'HIGH','type'=>'business','title'=>'Overall contribution profit is negative','detail'=>'Estimated contribution profit is '.number_format_i18n((float)$z['contribution_profit'],2).' BDT.','action'=>'Review spend, returns, COGS and courier assumptions before increasing acquisition.');usort($a,function($u,$v){$r=array('HIGH'=>0,'MEDIUM'=>1,'LOW'=>2);return ($r[$u['priority']]??9)<=>($r[$v['priority']]??9);});return array('days'=>$days,'model'=>$model,'recommendations'=>$a,'summary'=>$z);}
 public static function page(){if(!current_user_can('manage_woocommerce'))return;$days=self::period(isset($_GET['period'])?$_GET['period']:30);$model=SMF_Attribution_Model::normalize_model(isset($_GET['model'])?wp_unslash($_GET['model']):get_option('smf_attribution_model','last_touch'));$r=self::recommendations($days,$model);?>
<div class="wrap smf-wrap"><div class="smf-header"><div><h1>Decision Center</h1><p>Actionable merchant recommendations from profitability, campaign quality, courier health and tracking reliability.</p></div><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=smf-executive&period='.$days.'&model='.rawurlencode($model)));?>">← Executive Dashboard</a></div>
<form method="get" class="smf-period-bar"><input type="hidden" name="page" value="smf-decisions"><label>Attribution model <select name="model"><?php foreach(array('last_touch'=>'Last Touch','first_touch'=>'First Touch','first_last'=>'First + Last (50/50)','assisted'=>'Assisted') as $k=>$v):?><option value="<?php echo esc_attr($k);?>" <?php selected($model,$k);?>><?php echo esc_html($v);?></option><?php endforeach;?></select></label><?php foreach(array(7,30,90) as $p):?><a class="button <?php echo $days===$p?'button-primary':'';?>" href="<?php echo esc_url(admin_url('admin.php?page=smf-decisions&period='.$p.'&model='.rawurlencode($model)));?>"><?php echo $p;?> days</a><?php endforeach;?><button class="button">Apply</button></form>
<div class="smf-status <?php echo $r['recommendations']?'is-warning':'is-good';?>"><span class="smf-status-dot"></span><div><strong><?php echo $r['recommendations']?count($r['recommendations']).' recommendation(s)':'No action thresholds triggered';?></strong><small><?php echo esc_html($days);?>-day view · recommendations are advisory, not automatic spend/dispatch actions</small></div></div>
<div class="smf-panel"><h2>Recommended actions</h2><?php if($r['recommendations']):?><div class="smf-diagnostic-mini"><?php foreach($r['recommendations'] as $i=>$a):?><span><?php echo esc_html($a['priority'].' · '.$a['title']);?></span><b class="is-warning"><?php echo esc_html($a['detail'].' '.$a['action']);?></b><?php endforeach;?></div><?php else:?><p class="smf-muted">No campaign, courier, system or profitability rule crossed its current threshold.</p><?php endif;?></div>
<div class="smf-panel"><h2>Operating basis</h2><div class="smf-revenue-grid"><div><span>Contribution profit</span><strong><?php echo esc_html(number_format_i18n((float)$r['summary']['contribution_profit'],2));?> BDT</strong></div><div><span>Margin</span><strong><?php echo esc_html(number_format_i18n((float)$r['summary']['contribution_margin'],2));?>%</strong></div><div><span>Ad spend</span><strong><?php echo esc_html(number_format_i18n((float)$r['summary']['spend'],2));?> BDT</strong></div><div><span>ROAS</span><strong><?php echo esc_html(number_format_i18n((float)$r['summary']['roas'],2));?>×</strong></div></div></div>
<p class="smf-muted">Recommendations use estimated contribution economics and observed operational data. They never change ad budgets, orders or courier routing automatically.</p></div><?php }
}
