<?php
defined('ABSPATH') || exit;
class SMF_Executive {
 public static function init(){add_action('admin_menu',array(__CLASS__,'menu'),25);}
 public static function menu(){add_submenu_page('sync-meta-flow','Executive Dashboard','Executive Dashboard','manage_woocommerce','smf-executive',array(__CLASS__,'page'));}
 private static function period($days){$days=absint($days);return in_array($days,array(7,30,90),true)?$days:30;}
 private static function fmt($n){return number_format_i18n((float)$n,2);}
 private static function purchase_orders($days,$currency){global $wpdb;$t=$wpdb->prefix.'smf_order_events';$until=current_time('Y-m-d');$since=wp_date('Y-m-d',strtotime('-'.($days-1).' days',current_time('timestamp')));$ids=$wpdb->get_col($wpdb->prepare("SELECT DISTINCT order_id FROM $t WHERE event_type='purchase' AND created_at BETWEEN %s AND %s",$since.' 00:00:00',$until.' 23:59:59'));$count=0;if(!$ids)return 0;foreach($ids as $id){$o=wc_get_order((int)$id);if($o&&strtoupper((string)$o->get_currency())===strtoupper($currency))$count++;}return $count;}
 private static function attention($x,$courier,$queue,$purchase_orders){$a=array();$z=$x['summary'];$delivery=$purchase_orders>0?($z['delivered_orders']/$purchase_orders*100):100;$cancel=$purchase_orders>0?($z['cancelled_orders']/$purchase_orders*100):0;$return=$purchase_orders>0?($z['returned_orders']/$purchase_orders*100):0;if($purchase_orders>0&&$delivery<70)$a[]=array('title'=>'Low delivery rate','detail'=>self::fmt($delivery).'% of purchased orders reached delivered status.');if($purchase_orders>0&&$cancel>15)$a[]=array('title'=>'High cancellation','detail'=>self::fmt($cancel).'% of purchased orders are cancelled.');if($purchase_orders>0&&$return>15)$a[]=array('title'=>'High return rate','detail'=>self::fmt($return).'% of purchased orders are returned.');if($z['contribution_profit']<0)$a[]=array('title'=>'Negative contribution profit','detail'=>'Estimated contribution profit is '.self::fmt($z['contribution_profit']).' '.$x['currency'].'.');foreach($courier as $p){if(isset($p['health_label'])&&$p['health_label']==='DEGRADED')$a[]=array('title'=>'Degraded courier: '.$p['provider'],'detail'=>'Health score '.$p['health_score'].'/100; combined score '.$p['combined_score'].'/100.');}if((int)($queue['failed']??0)>0)$a[]=array('title'=>'CAPI failures','detail'=>(int)$queue['failed'].' failed event(s) need attention.');return $a;}
 public static function page(){if(!current_user_can('manage_woocommerce'))return;$days=self::period(isset($_GET['period'])?$_GET['period']:30);$model=SMF_Attribution_Model::normalize_model(isset($_GET['model'])?wp_unslash($_GET['model']):get_option('smf_attribution_model','last_touch'));$x=SMF_Profitability::report($days,'BDT',$model);$z=$x['summary'];$purchase_orders=self::purchase_orders($days,'BDT');$delivery_rate=$purchase_orders>0?($z['delivered_orders']/$purchase_orders*100):0;$cancel_rate=$purchase_orders>0?($z['cancelled_orders']/$purchase_orders*100):0;$return_rate=$purchase_orders>0?($z['returned_orders']/$purchase_orders*100):0;$courier=class_exists('SMF_Courier_Operations')?SMF_Courier_Operations::provider_intelligence($days):array();$queue=class_exists('SMF_Meta_CAPI')?SMF_Meta_CAPI::get_queue_stats():array('pending'=>0,'sent'=>0,'failed'=>0);$alerts=self::attention($x,$courier,$queue,$purchase_orders);$campaigns=$x['campaigns'];$top_profit=$campaigns;$best_roas=$campaigns;$best_delivery=$campaigns;usort($top_profit,function($a,$b){return $b['profit']<=>$a['profit'];});usort($best_roas,function($a,$b){return $b['roas']<=>$a['roas'];});usort($best_delivery,function($a,$b){$ad=$a['orders']?($a['delivered_orders']/$a['orders']):0;$bd=$b['orders']?($b['delivered_orders']/$b['orders']):0;return $bd<=>$ad;});?>
<div class="wrap smf-wrap"><div class="smf-header"><div><h1>Executive Dashboard</h1><p>One operating view for revenue, profitability, attribution, delivery quality and system health.</p></div><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=smf-profitability&period='.$days.'&model='.rawurlencode($model)));?>">Profitability Settings</a></div>
<form method="get" class="smf-period-bar"><input type="hidden" name="page" value="smf-executive"><label>Attribution model <select name="model"><?php foreach(array('last_touch'=>'Last Touch','first_touch'=>'First Touch','first_last'=>'First + Last (50/50)','assisted'=>'Assisted') as $k=>$v):?><option value="<?php echo esc_attr($k);?>" <?php selected($model,$k);?>><?php echo esc_html($v);?></option><?php endforeach;?></select></label><?php foreach(array(7,30,90) as $p):?><a class="button <?php echo $days===$p?'button-primary':'';?>" href="<?php echo esc_url(admin_url('admin.php?page=smf-executive&period='.$p.'&model='.rawurlencode($model)));?>"><?php echo $p;?> days</a><?php endforeach;?><button class="button">Apply</button></form>
<div class="smf-status <?php echo $alerts?'is-warning':'is-good';?>"><span class="smf-status-dot"></span><div><strong><?php echo $alerts?count($alerts).' item(s) need attention':'Operating picture looks healthy';?></strong><small><?php echo esc_html($days);?>-day view · <?php echo esc_html(ucwords(str_replace('_',' ',$model)));?> attribution</small></div></div>
<div class="smf-cards"><div class="smf-card"><span>Delivered Revenue</span><strong><?php echo self::fmt($z['delivered_revenue']);?></strong><small>Realized-order basis · BDT</small></div><div class="smf-card"><span>Contribution Profit</span><strong><?php echo self::fmt($z['contribution_profit']);?></strong><small>Estimated after assumptions + ad spend</small></div><div class="smf-card"><span>Ad Spend</span><strong><?php echo self::fmt($z['spend']);?></strong><small>Matched campaign spend</small></div><div class="smf-card"><span>ROAS</span><strong><?php echo self::fmt($z['roas']);?>×</strong><small>Delivered revenue / spend</small></div><div class="smf-card"><span>Delivery Rate</span><strong><?php echo self::fmt($delivery_rate);?>%</strong><small><?php echo esc_html($z['delivered_orders']);?> / <?php echo esc_html($purchase_orders);?> purchased</small></div><div class="smf-card"><span>Margin</span><strong><?php echo self::fmt($z['contribution_margin']);?>%</strong><small>Contribution margin</small></div></div>
<div class="smf-panel"><h2>What needs attention?</h2><?php if($alerts):?><div class="smf-diagnostic-mini"><?php foreach($alerts as $a):?><span><?php echo esc_html($a['title']);?></span><b class="is-warning"><?php echo esc_html($a['detail']);?></b><?php endforeach;?></div><?php else:?><p class="smf-muted">No executive alerts crossed the current operating thresholds.</p><?php endif;?></div>
<div class="smf-panel"><h2>Order quality</h2><div class="smf-revenue-grid"><div><span>Purchased orders</span><strong><?php echo esc_html($purchase_orders);?></strong></div><div><span>Delivery rate</span><strong><?php echo self::fmt($delivery_rate);?>%</strong></div><div><span>Cancellation rate</span><strong><?php echo self::fmt($cancel_rate);?>%</strong></div><div><span>Return rate</span><strong><?php echo self::fmt($return_rate);?>%</strong></div></div></div>
<div class="smf-panel"><h2>Campaign leaderboard</h2><div class="smf-table-wrap"><table class="smf-table"><thead><tr><th>Top profit</th><th>Profit</th><th>Best ROAS</th><th>ROAS</th><th>Best delivery quality</th><th>Delivery</th></tr></thead><tbody><tr><td><?php echo !empty($top_profit[0])?esc_html($top_profit[0]['campaign']):'—';?></td><td><?php echo !empty($top_profit[0])?self::fmt($top_profit[0]['profit']):'—';?></td><td><?php echo !empty($best_roas[0])?esc_html($best_roas[0]['campaign']):'—';?></td><td><?php echo !empty($best_roas[0])?self::fmt($best_roas[0]['roas']).'×':'—';?></td><td><?php echo !empty($best_delivery[0])?esc_html($best_delivery[0]['campaign']):'—';?></td><td><?php echo !empty($best_delivery[0])&&$best_delivery[0]['orders']?self::fmt($best_delivery[0]['delivered_orders']/$best_delivery[0]['orders']*100).'%':'—';?></td></tr></tbody></table></div><p class="smf-muted">Campaign spend is only considered matched when the spend table uses the same campaign identifier.</p></div>
<div class="smf-panel"><h2>Courier leaderboard</h2><div class="smf-table-wrap"><table class="smf-table"><thead><tr><th>Provider</th><th>Health</th><th>Combined</th><th>Delivered</th><th>SLA breaches</th><th>Financial impact</th></tr></thead><tbody><?php if($courier):foreach(array_slice($courier,0,10) as $p):?><tr><td><strong><?php echo esc_html($p['provider']);?></strong></td><td><?php echo esc_html($p['health_score']);?>/100 · <?php echo esc_html($p['health_label']);?></td><td><?php echo esc_html($p['combined_score']);?>/100</td><td><?php echo esc_html($p['delivered']);?></td><td><?php echo esc_html($p['delivery_sla_breaches']);?></td><td><?php echo self::fmt($p['impact_value']);?> BDT</td></tr><?php endforeach;else:?><tr><td colspan="6">No courier intelligence yet.</td></tr><?php endif;?></tbody></table></div></div>
<div class="smf-panel"><h2>System health</h2><div class="smf-diagnostic-mini"><span>CAPI pending</span><b><?php echo esc_html($queue['pending']??0);?></b><span>CAPI failed</span><b class="<?php echo !empty($queue['failed'])?'is-warning':'is-good';?>"><?php echo esc_html($queue['failed']??0);?></b><span>Courier providers</span><b><?php echo esc_html(count($courier));?></b><span>Attribution</span><b><?php echo esc_html(ucwords(str_replace('_',' ',$model)));?></b></div></div>
<div class="smf-panel"><h2>Quick links</h2><p><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=smf-profitability&period='.$days.'&model='.rawurlencode($model)));?>">Profitability</a> <a class="button" href="<?php echo esc_url(admin_url('admin.php?page=smf-courier-operations'));?>">Courier Operations</a> <a class="button" href="<?php echo esc_url(admin_url('admin.php?page=smf-diagnostics'));?>">Diagnostics</a> <a class="button" href="<?php echo esc_url(admin_url('admin.php?page=smf-settings'));?>">Setup & Settings</a></p></div>
<p class="smf-muted">Contribution profit is an operating estimate, not accounting-grade net profit. Alert thresholds are practical merchant heuristics and should be tuned to the store.</p></div>
<?php }
}
