<?php
defined('ABSPATH') || exit;

class SMF_Spend {
    public static function init() {
        add_action('admin_menu', array(__CLASS__, 'menu'));
        add_action('admin_post_smf_save_spend', array(__CLASS__, 'save'));
        add_action('admin_post_smf_delete_spend', array(__CLASS__, 'delete'));
    }
    public static function menu() { add_submenu_page('sync-meta-flow','Ad Spend & ROAS','Ad Spend & ROAS','manage_woocommerce','smf-spend',array(__CLASS__,'render_page')); }
    public static function save() {
        if (!current_user_can('manage_woocommerce')) wp_die('Unauthorized'); check_admin_referer('smf_save_spend'); global $wpdb;
        $date=isset($_POST['spend_date'])?sanitize_text_field(wp_unslash($_POST['spend_date'])):'';
        $campaign_id=isset($_POST['campaign_id'])?sanitize_text_field(wp_unslash($_POST['campaign_id'])):'';
        $adset_id=isset($_POST['adset_id'])?sanitize_text_field(wp_unslash($_POST['adset_id'])):'';
        $ad_id=isset($_POST['ad_id'])?sanitize_text_field(wp_unslash($_POST['ad_id'])):'';
        $amount=isset($_POST['amount'])?(float)wp_unslash($_POST['amount']):0;
        $currency=isset($_POST['currency'])?strtoupper(sanitize_text_field(wp_unslash($_POST['currency']))):'BDT';
        if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$amount<0||!preg_match('/^[A-Z]{3}$/',$currency))wp_die('Invalid spend data.');
        $wpdb->insert($wpdb->prefix.'smf_campaign_spend',array('spend_date'=>$date,'campaign_id'=>$campaign_id,'adset_id'=>$adset_id,'ad_id'=>$ad_id,'amount'=>$amount,'currency'=>$currency,'created_at'=>current_time('mysql')));
        wp_safe_redirect(admin_url('admin.php?page=smf-spend&updated=1'));exit;
    }
    public static function delete(){if(!current_user_can('manage_woocommerce'))wp_die('Unauthorized');$id=isset($_GET['id'])?absint($_GET['id']):0;check_admin_referer('smf_delete_spend_'.$id);global $wpdb;$wpdb->delete($wpdb->prefix.'smf_campaign_spend',array('id'=>$id),array('%d'));wp_safe_redirect(admin_url('admin.php?page=smf-spend'));exit;}
    public static function total_spend($since=null,$until=null){global $wpdb;$where='1=1';$args=array();if($since){$where.=' AND spend_date >= %s';$args[]=$since;}if($until){$where.=' AND spend_date <= %s';$args[]=$until;}$sql="SELECT COALESCE(SUM(amount),0) FROM {$wpdb->prefix}smf_campaign_spend WHERE $where";return $args?(float)$wpdb->get_var($wpdb->prepare($sql,$args)):(float)$wpdb->get_var($sql);}
    public static function rows($limit=50){global $wpdb;return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}smf_campaign_spend ORDER BY spend_date DESC,id DESC LIMIT %d",max(1,min(200,absint($limit)))));}

    /** Match spend to orders by exact ad -> ad set -> campaign ID, then calculate milestone-aware revenue. */
    public static function performance($since,$until,$currency='BDT') {
        global $wpdb;$spend_table=$wpdb->prefix.'smf_campaign_spend';$event_table=$wpdb->prefix.'smf_order_events';
        $spend=$wpdb->get_results($wpdb->prepare("SELECT campaign_id,adset_id,ad_id,amount,currency FROM $spend_table WHERE spend_date BETWEEN %s AND %s AND currency=%s ORDER BY campaign_id,adset_id,ad_id",$since,$until,$currency));
        $groups=array();
        foreach($spend as $r){$key=$r->ad_id!==''?'ad:'.$r->ad_id:($r->adset_id!==''?'adset:'.$r->adset_id:($r->campaign_id!==''?'campaign:'.$r->campaign_id:'unattributed'));if(!isset($groups[$key]))$groups[$key]=array('key'=>$key,'campaign_id'=>$r->campaign_id,'adset_id'=>$r->adset_id,'ad_id'=>$r->ad_id,'currency'=>$r->currency,'spend'=>0,'orders'=>0,'purchase_revenue'=>0,'delivered_orders'=>0,'delivered_revenue'=>0,'cancelled_orders'=>0,'returned_orders'=>0,'returned_revenue'=>0);$groups[$key]['spend']+=(float)$r->amount;}

        /* First identify purchases in the selected period; then load their complete history so a later delivery/return still affects ROAS. */
        $purchase_rows=$wpdb->get_results($wpdb->prepare("SELECT order_id FROM $event_table WHERE event_type='purchase' AND created_at >= %s AND created_at < DATE_ADD(%s,INTERVAL 1 DAY)", $since.' 00:00:00',$until.' 00:00:00'));
        $ids=array();foreach($purchase_rows as $r){$id=(int)$r->order_id;if($id)$ids[$id]=true;}if(!$ids)return array('summary'=>self::empty_summary(),'groups'=>array_values($groups));
        $placeholders=implode(',',array_fill(0,count($ids),'%d'));$event_args=array_keys($ids);$events=$wpdb->get_results($wpdb->prepare("SELECT order_id,event_type,new_status,metadata,created_at,id FROM $event_table WHERE order_id IN ($placeholders) ORDER BY order_id ASC,created_at ASC,id ASC",$event_args));
        $orders=array();foreach($events as $e){$id=(int)$e->order_id;if(!isset($orders[$id]))$orders[$id]=array('total'=>0,'currency'=>'','campaign_id'=>'','adset_id'=>'','ad_id'=>'','purchased'=>false,'delivered'=>false,'cancelled'=>false,'returned'=>false);$m=$e->metadata?json_decode($e->metadata,true):array();if(isset($m['order_total']))$orders[$id]['total']=(float)$m['order_total'];foreach(array('currency','campaign_id','adset_id','ad_id') as $f)if(!empty($m[$f]))$orders[$id][$f]=sanitize_text_field($m[$f]);if($e->event_type==='purchase')$orders[$id]['purchased']=true;$s=(string)$e->new_status;if(in_array($s,array('smf-delivered','completed'),true))$orders[$id]['delivered']=true;if($s==='cancelled')$orders[$id]['cancelled']=true;if(in_array($s,array('smf-returned','refunded'),true))$orders[$id]['returned']=true;}
        foreach($orders as $o){if(!$o['purchased']||strtoupper($o['currency'])!==strtoupper($currency))continue;$key=$o['ad_id']!==''?'ad:'.$o['ad_id']:($o['adset_id']!==''?'adset:'.$o['adset_id']:($o['campaign_id']!==''?'campaign:'.$o['campaign_id']:''));if(!$key||!isset($groups[$key]))continue;$v=(float)$o['total'];$groups[$key]['orders']++;$groups[$key]['purchase_revenue']+=$v;if($o['delivered']){$groups[$key]['delivered_orders']++;$groups[$key]['delivered_revenue']+=$v;}if($o['cancelled'])$groups[$key]['cancelled_orders']++;if($o['returned']){$groups[$key]['returned_orders']++;$groups[$key]['returned_revenue']+=$v;}}
        $summary=self::empty_summary();foreach($groups as &$g){$g['net_realized_revenue']=max(0,$g['delivered_revenue']-$g['returned_revenue']);$g['purchase_roas']=$g['spend']>0?$g['purchase_revenue']/$g['spend']:0;$g['delivered_roas']=$g['spend']>0?$g['delivered_revenue']/$g['spend']:0;$g['net_roas']=$g['spend']>0?$g['net_realized_revenue']/$g['spend']:0;$g['cpa']=$g['delivered_orders']>0?$g['spend']/$g['delivered_orders']:0;$g['cancel_rate']=$g['orders']>0?($g['cancelled_orders']/$g['orders'])*100:0;$g['return_rate']=$g['delivered_orders']>0?($g['returned_orders']/$g['delivered_orders'])*100:0;$g['decision']=$g['spend']<=0?'NO SPEND':($g['net_roas']>=3?'SCALE':($g['net_roas']>=1?'WATCH':'KILL'));foreach(array('spend','orders','purchase_revenue','delivered_orders','delivered_revenue','cancelled_orders','returned_orders','returned_revenue') as $f)$summary[$f]+=$g[$f];}unset($g);
        $summary['net_realized_revenue']=max(0,$summary['delivered_revenue']-$summary['returned_revenue']);$summary['purchase_roas']=$summary['spend']>0?$summary['purchase_revenue']/$summary['spend']:0;$summary['delivered_roas']=$summary['spend']>0?$summary['delivered_revenue']/$summary['spend']:0;$summary['net_roas']=$summary['spend']>0?$summary['net_realized_revenue']/$summary['spend']:0;$summary['cpa']=$summary['delivered_orders']>0?$summary['spend']/$summary['delivered_orders']:0;$summary['cancel_rate']=$summary['orders']>0?($summary['cancelled_orders']/$summary['orders'])*100:0;$summary['return_rate']=$summary['delivered_orders']>0?($summary['returned_orders']/$summary['delivered_orders'])*100:0;usort($groups,function($a,$b){return $b['net_roas']<=>$a['net_roas'];});return array('summary'=>$summary,'groups'=>array_values($groups));
    }
    private static function empty_summary(){return array('spend'=>0,'orders'=>0,'purchase_revenue'=>0,'delivered_orders'=>0,'delivered_revenue'=>0,'cancelled_orders'=>0,'returned_orders'=>0,'returned_revenue'=>0,'net_realized_revenue'=>0,'purchase_roas'=>0,'delivered_roas'=>0,'net_roas'=>0,'cpa'=>0,'cancel_rate'=>0,'return_rate'=>0);}
    private static function range($period){$days=in_array($period,array(7,30,90),true)?(int)$period:30;$until=current_time('Y-m-d');$since=wp_date('Y-m-d',strtotime('-'.($days-1).' days',current_time('timestamp')));return array($since,$until,$days);}

    public static function render_page(){if(!current_user_can('manage_woocommerce'))return;$period=isset($_GET['period'])?absint($_GET['period']):30;list($since,$until,$days)=self::range($period);$currency=isset($_GET['currency'])?strtoupper(sanitize_text_field(wp_unslash($_GET['currency']))):'BDT';$report=self::performance($since,$until,$currency);$s=$report['summary'];$rows=self::rows();?>
    <div class="wrap smf-wrap smf-settings"><div class="smf-header"><div><h1>Ad Spend & ROAS</h1><p>Measure Purchase, Delivered and Net Realized ROAS from your WooCommerce order flow.</p></div><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=sync-meta-flow')); ?>">← Dashboard</a></div>
    <div class="smf-period-bar"><strong><?php echo esc_html($currency); ?> · ROAS period</strong><?php foreach(array(7,30,90) as $p):?><a class="button <?php echo $days===$p?'button-primary':'';?>" href="<?php echo esc_url(admin_url('admin.php?page=smf-spend&period='.$p.'&currency='.rawurlencode($currency)));?>"><?php echo esc_html($p);?> days</a><?php endforeach;?></div>
    <div class="smf-cards"><div class="smf-card"><span>Ad Spend</span><strong><?php echo esc_html(number_format_i18n($s['spend'],2));?></strong><small><?php echo esc_html($since.' → '.$until);?></small></div><div class="smf-card"><span>Purchase ROAS</span><strong><?php echo esc_html(number_format_i18n($s['purchase_roas'],2));?>×</strong><small><?php echo esc_html(number_format_i18n($s['purchase_revenue'],2));?> purchase revenue</small></div><div class="smf-card"><span>Delivered ROAS</span><strong><?php echo esc_html(number_format_i18n($s['delivered_roas'],2));?>×</strong><small><?php echo esc_html(number_format_i18n($s['delivered_revenue'],2));?> delivered revenue</small></div><div class="smf-card"><span>Net Realized ROAS</span><strong><?php echo esc_html(number_format_i18n($s['net_roas'],2));?>×</strong><small>Delivered − returned revenue</small></div></div>
    <div class="smf-revenue-grid"><div><span>Net realized revenue</span><strong><?php echo esc_html(number_format_i18n($s['net_realized_revenue'],2));?></strong></div><div><span>Delivered orders</span><strong><?php echo esc_html($s['delivered_orders']);?></strong></div><div><span>Cost / delivered order</span><strong><?php echo esc_html(number_format_i18n($s['cpa'],2));?></strong></div><div><span>Cancel / return</span><strong><?php echo esc_html(number_format_i18n($s['cancel_rate'],1));?>% / <?php echo esc_html(number_format_i18n($s['return_rate'],1));?>%</strong></div></div>
    <div class="smf-panel"><h2>ROAS Intelligence</h2><p class="smf-muted">Matching uses exact Ad ID first, then Ad Set ID, then Campaign ID. Historical status events are retained, so an order delivered or returned after purchase still updates the selected purchase cohort.</p><div class="smf-table-wrap"><table class="smf-table"><thead><tr><th>Level</th><th>Campaign</th><th>Ad Set</th><th>Ad</th><th>Spend</th><th>Orders</th><th>Purchase ROAS</th><th>Delivered ROAS</th><th>Net ROAS</th><th>CPA</th><th>Decision</th></tr></thead><tbody><?php if($report['groups']):foreach($report['groups'] as $g):$level=strpos($g['key'],'ad:')===0?'Ad':(strpos($g['key'],'adset:')===0?'Ad Set':'Campaign');?><tr><td><?php echo esc_html($level);?></td><td><?php echo esc_html($g['campaign_id']?:'—');?></td><td><?php echo esc_html($g['adset_id']?:'—');?></td><td><?php echo esc_html($g['ad_id']?:'—');?></td><td><?php echo esc_html(number_format_i18n($g['spend'],2).' '.$g['currency']);?></td><td><?php echo esc_html($g['orders']);?></td><td><?php echo esc_html(number_format_i18n($g['purchase_roas'],2));?>×</td><td><?php echo esc_html(number_format_i18n($g['delivered_roas'],2));?>×</td><td><strong><?php echo esc_html(number_format_i18n($g['net_roas'],2));?>×</strong></td><td><?php echo esc_html(number_format_i18n($g['cpa'],2));?></td><td><span class="smf-decision smf-decision-<?php echo esc_attr(strtolower(str_replace(' ','-',$g['decision'])));?>"><?php echo esc_html($g['decision']);?></span></td></tr><?php endforeach;else:?><tr><td colspan="11">No spend data for this period. Add daily spend below using the same IDs captured on orders.</td></tr><?php endif;?></tbody></table></div><p class="smf-muted">Default heuristic: <strong>SCALE</strong> ≥ 3× net ROAS · <strong>WATCH</strong> 1–2.99× · <strong>KILL</strong> &lt; 1×. Adjust for your actual margin and fulfillment economics.</p></div>
    <div class="smf-setup-grid"><div class="smf-panel"><h2>Add daily spend</h2><p class="smf-muted">Spend is manually recorded for now. Meta Ads Insights API sync is the next integration.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="smf_save_spend"><?php wp_nonce_field('smf_save_spend');?><p><label>Date<br><input class="smf-input" type="date" name="spend_date" value="<?php echo esc_attr(current_time('Y-m-d'));?>" required></label></p><p><label>Campaign ID<br><input class="smf-input" name="campaign_id" placeholder="Meta campaign ID"></label></p><p><label>Ad Set ID<br><input class="smf-input" name="adset_id" placeholder="Optional"></label></p><p><label>Ad ID<br><input class="smf-input" name="ad_id" placeholder="Optional"></label></p><p><label>Spend<br><input class="smf-input" type="number" name="amount" min="0" step="0.01" required></label></p><p><label>Currency<br><input class="smf-input" name="currency" value="BDT" maxlength="3" pattern="[A-Za-z]{3}"></label></p><?php submit_button('Save Spend');?></form></div><div class="smf-panel"><h2>Recorded spend</h2><div class="smf-table-wrap"><table class="smf-table"><thead><tr><th>Date</th><th>Campaign</th><th>Ad Set</th><th>Ad</th><th>Spend</th><th></th></tr></thead><tbody><?php if($rows):foreach($rows as $r):?><tr><td><?php echo esc_html($r->spend_date);?></td><td><?php echo esc_html($r->campaign_id?:'—');?></td><td><?php echo esc_html($r->adset_id?:'—');?></td><td><?php echo esc_html($r->ad_id?:'—');?></td><td><?php echo esc_html(number_format_i18n((float)$r->amount,2).' '.$r->currency);?></td><td><a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=smf_delete_spend&id='.(int)$r->id),'smf_delete_spend_'.(int)$r->id));?>" onclick="return confirm('Delete this spend entry?')">Delete</a></td></tr><?php endforeach;else:?><tr><td colspan="6">No spend entries yet.</td></tr><?php endif;?></tbody></table></div></div></div></div><?php }
}
