<?php
defined('ABSPATH') || exit;
class SMF_Courier_Operations {
 public static function init(){add_action('admin_menu',array(__CLASS__,'menu'),35);add_action('admin_post_smf_save_courier_ops',array(__CLASS__,'save'));}
 public static function menu(){add_submenu_page('sync-meta-flow','Courier Operations','Courier Operations','manage_woocommerce','smf-courier-operations',array(__CLASS__,'page'));}
 private static function settings(){return array('default_provider'=>sanitize_key((string)get_option('smf_courier_provider','generic')),'risk_window'=>max(1,min(365,absint(get_option('smf_courier_risk_window',90)))));}
 private static function status_key($s){$s=strtolower(sanitize_key((string)$s));if(in_array($s,array('completed','smf-delivered'),true))return'delivered';if(in_array($s,array('smf-returned','refunded'),true))return'returned';if(in_array($s,array('cancelled','failed'),true))return'cancelled';if($s==='smf-shipped')return'shipped';if($s==='smf-confirmed')return'confirmed';return'other';}
 public static function customer_risk($order_id){$o=wc_get_order(absint($order_id));if(!$o)return array('score'=>0,'label'=>'Unknown','orders'=>0,'delivered'=>0,'returned'=>0,'cancelled'=>0);$email=sanitize_email($o->get_billing_email());$phone=preg_replace('/\D+/','',(string)$o->get_billing_phone());$window=self::settings()['risk_window'];$since=gmdate('Y-m-d H:i:s',time()-$window*DAY_IN_SECONDS);$a=array('limit'=>100,'return'=>'ids','exclude'=>array($o->get_id()),'date_created'=>'>='.$since);if($email)$a['billing_email']=$email;elseif($phone)$a['billing_phone']=$phone;else return array('score'=>0,'label'=>'Unknown','orders'=>0,'delivered'=>0,'returned'=>0,'cancelled'=>0);$ids=wc_get_orders($a);$st=array('orders'=>0,'delivered'=>0,'returned'=>0,'cancelled'=>0);foreach($ids as $id){$prev=wc_get_order($id);if(!$prev)continue;$st['orders']++;$k=self::status_key($prev->get_status());if($k==='delivered')$st['delivered']++;elseif($k==='returned')$st['returned']++;elseif($k==='cancelled')$st['cancelled']++;}$score=50;if($st['orders']>0)$score=50+($st['delivered']/$st['orders'])*40-($st['returned']/$st['orders'])*60-($st['cancelled']/$st['orders'])*30;$score=max(0,min(100,round($score)));return array_merge($st,array('score'=>$score,'label'=>$score>=75?'LOW RISK':($score>=45?'MEDIUM RISK':'HIGH RISK')));}
 public static function recommend_provider($o){$p=self::settings()['default_provider'];$r=self::customer_risk($o->get_id());return array('provider'=>$p,'risk'=>$r,'reason'=>$p!=='generic'?'Configured default provider':($r['label']==='HIGH RISK'?'High-risk customer: review before dispatch':'No native provider selected'));}
 private static function orders_window($days){return wc_get_orders(array('limit'=>200,'type'=>'shop_order','date_created'=>'>='.gmdate('Y-m-d H:i:s',time()-$days*DAY_IN_SECONDS),'orderby'=>'date','order'=>'DESC','return'=>'objects'));}
 private static function provider_stats($days){global $wpdb;$t=$wpdb->prefix.'smf_courier_events';$since=gmdate('Y-m-d H:i:s',time()-$days*DAY_IN_SECONDS);$r=$wpdb->get_results($wpdb->prepare("SELECT provider,COUNT(*) events,SUM(result='processed') processed,SUM(result='failed') failed FROM $t WHERE received_at >= %s GROUP BY provider ORDER BY events DESC",$since),ARRAY_A);return$r?:array();}
 private static function queue(){ $out=array();foreach(self::orders_window(30) as $o){$k=self::status_key($o->get_status());if(!in_array($k,array('confirmed','shipped'),true)||$o->get_meta('_smf_tracking_number'))continue;$risk=self::customer_risk($o->get_id());$rec=self::recommend_provider($o);$out[]=array('id'=>$o->get_id(),'date'=>$o->get_date_created()?$o->get_date_created()->date_i18n('Y-m-d H:i'):'','total'=>$o->get_total(),'status'=>$o->get_status(),'risk'=>$risk,'provider'=>$rec['provider'],'reason'=>$rec['reason']);}return$out;}
 public static function save(){if(!current_user_can('manage_woocommerce'))wp_die('Unauthorized');check_admin_referer('smf_save_courier_ops');update_option('smf_courier_risk_window',max(1,min(365,absint($_POST['risk_window']??90))),false);wp_safe_redirect(admin_url('admin.php?page=smf-courier-operations&updated=1'));exit;}
 public static function page(){if(!current_user_can('manage_woocommerce'))return;$s=self::settings();$q=self::queue();$p=self::provider_stats($s['risk_window']);?><div class="wrap smf-wrap smf-settings"><div class="smf-header"><div><h1>Courier Operations</h1><p>Dispatch queue, customer-risk signals and courier webhook health.</p></div><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=sync-meta-flow'));?>">← Dashboard</a></div><div class="smf-panel"><h2>Risk policy</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="smf_save_courier_ops"><?php wp_nonce_field('smf_save_courier_ops');?><p><label>Risk history window (days)<br><input class="small-text" type="number" min="1" max="365" name="risk_window" value="<?php echo esc_attr($s['risk_window']);?>"></label></p><?php submit_button('Save Risk Policy');?></form><p class="smf-muted">Risk is a dispatch signal, not a fraud verdict. Customer history is limited to this configured window. Shipment creation remains provider-specific and manual through the existing courier adapter.</p></div><div class="smf-panel"><h2>Dispatch queue <span class="smf-muted">(last 30 days)</span></h2><div class="smf-table-wrap"><table class="smf-table"><thead><tr><th>Order</th><th>Date</th><th>Total</th><th>Status</th><th>Risk</th><th>Provider</th><th>Reason</th></tr></thead><tbody><?php if(!$q):?><tr><td colspan="7">No confirmed/shipped orders are waiting for courier tracking.</td></tr><?php else:foreach($q as $r):?><tr><td><a href="<?php echo esc_url(admin_url('post.php?post='.$r['id'].'&action=edit'));?>">#<?php echo esc_html($r['id']);?></a></td><td><?php echo esc_html($r['date']);?></td><td><?php echo esc_html(number_format_i18n((float)$r['total'],2));?></td><td><?php echo esc_html(wc_get_order_status_name($r['status']));?></td><td><strong><?php echo esc_html($r['risk']['label']);?></strong> · <?php echo esc_html($r['risk']['score']);?>/100</td><td><?php echo esc_html(ucfirst($r['provider']));?></td><td><?php echo esc_html($r['reason']);?></td></tr><?php endforeach;endif;?></tbody></table></div></div><div class="smf-panel"><h2>Courier webhook performance</h2><div class="smf-table-wrap"><table class="smf-table"><thead><tr><th>Provider</th><th>Events</th><th>Processed</th><th>Failed</th></tr></thead><tbody><?php if(!$p):?><tr><td colspan="4">No courier events recorded in this window.</td></tr><?php else:foreach($p as $r):?><tr><td><?php echo esc_html(ucfirst($r['provider']));?></td><td><?php echo esc_html($r['events']);?></td><td><?php echo esc_html($r['processed']);?></td><td><?php echo esc_html($r['failed']);?></td></tr><?php endforeach;endif;?></tbody></table></div></div><div class="smf-panel"><h2>Routing policy</h2><p class="smf-muted">Configured-provider recommendation plus customer-risk context. Pathao and RedX are not called until documented native adapters are available.</p></div></div><?php }
}
