<?php
defined('ABSPATH') || exit;

class SMF_Attribution_Report {
    public static function init(){add_action('admin_menu',array(__CLASS__,'menu'));}
    public static function menu(){add_submenu_page('sync-meta-flow','Attribution Models','Attribution Models','manage_woocommerce','smf-attribution',array(__CLASS__,'render'));}
    public static function render(){if(!current_user_can('manage_woocommerce'))return;$metrics=SMF_Order_Events::get_flow_metrics();$rows=$metrics['campaigns'];usort($rows,function($a,$b){return ($b['first_touch']+$b['last_touch'])<=>($a['first_touch']+$a['last_touch']);});?>
    <div class="wrap smf-wrap"><div class="smf-header"><div><h1>Attribution Models</h1><p>Compare first-touch discovery, last-touch conversion and assisted campaign influence.</p></div><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=sync-meta-flow')); ?>">← Dashboard</a></div>
    <div class="smf-cards"><div class="smf-card"><span>Tracked Orders</span><strong><?php echo esc_html($metrics['orders']);?></strong><small>Orders with flow history</small></div><div class="smf-card"><span>First-touch Credits</span><strong><?php echo esc_html($metrics['orders']);?></strong><small>Discovery model</small></div><div class="smf-card"><span>Last-touch Credits</span><strong><?php echo esc_html($metrics['orders']);?></strong><small>Conversion model</small></div><div class="smf-card"><span>Assisted Conversions</span><strong><?php echo esc_html($metrics['assisted_orders']);?></strong><small>First and last campaign differ</small></div></div>
    <div class="smf-panel"><h2>Campaign Attribution Comparison</h2><p class="smf-muted">First-touch answers “who introduced the customer?” Last-touch answers “who was closest to purchase?” Assisted shows campaigns that introduced a customer who later converted through another campaign.</p><div class="smf-table-wrap"><table class="smf-table"><thead><tr><th>Campaign</th><th>First-touch</th><th>Last-touch</th><th>Assisted</th><th>Last-touch orders</th><th>Delivered revenue</th></tr></thead><tbody><?php if($rows):foreach($rows as $row):?><tr><td><strong><?php echo esc_html($row['campaign']);?></strong></td><td><?php echo esc_html($row['first_touch']);?></td><td><?php echo esc_html($row['last_touch']);?></td><td><?php echo esc_html($row['assisted']);?></td><td><?php echo esc_html($row['orders']);?></td><td><strong><?php echo esc_html(number_format_i18n($row['delivered_revenue'],2));?></strong></td></tr><?php endforeach;else:?><tr><td colspan="6">No attribution data yet.</td></tr><?php endif;?></tbody></table></div></div>
    <div class="smf-panel"><h2>Customer Journey</h2><p class="smf-muted">The session preserves the original first-touch record while later attributable visits update last-touch. Both are copied to the order at purchase.</p><div class="smf-flow"><b>First ad</b><span>→</span><b>Returning visit</b><span>→</span><b>New campaign</b><span>→</span><b>Purchase</b><span>→</span><b>Delivery</b></div></div>
    </div><?php }
}
