<?php
defined('ABSPATH') || exit;

class SMF_Meta_CAPI {
    const MAX_ATTEMPTS=5; const LOCK_KEY='smf_capi_queue_lock'; const LOCK_TTL=120; const BATCH_SIZE=10;
    public static function init(){add_filter('cron_schedules',array(__CLASS__,'cron_schedules'));add_action('woocommerce_checkout_order_processed',array(__CLASS__,'send_purchase'),20,3);add_action('woocommerce_order_status_completed',array(__CLASS__,'send_delivered'),20);add_action('woocommerce_order_status_smf-delivered',array(__CLASS__,'send_delivered'),20);add_action('smf_process_capi_queue',array(__CLASS__,'process_queue'));add_action('wp_ajax_smf_test_connection',array(__CLASS__,'test_connection'));if(!wp_next_scheduled('smf_process_capi_queue'))wp_schedule_event(time()+60,'five_minutes','smf_process_capi_queue');}
    public static function cron_schedules($s){if(!isset($s['five_minutes']))$s['five_minutes']=array('interval'=>300,'display'=>'Every 5 minutes');return $s;}
    public static function send_purchase($order_id,$posted_data=null,$order=null){$order=$order instanceof WC_Order?$order:wc_get_order($order_id);if(!$order||!self::configured())return;$id=$order->get_meta('_smf_purchase_event_id');if(!$id){$id='smf-purchase-'.$order->get_id().'-'.wp_generate_uuid4();$order->update_meta_data('_smf_purchase_event_id',$id);$order->save();}self::queue_event($order->get_id(),'Purchase',$id,self::purchase_payload($order,$id));}
    public static function send_delivered($order_id){$order=wc_get_order($order_id);if(!$order||!self::configured())return;$delivered_at=$order->get_meta('_smf_delivered_at');if(!$delivered_at||!is_numeric($delivered_at)){$delivered_at=time();$order->update_meta_data('_smf_delivered_at',$delivered_at);$order->save();}$id='smf-delivered-'.$order->get_id();self::queue_event($order->get_id(),'OrderDelivered',$id,self::delivered_payload($order,$id));}
    private static function purchase_payload($o,$id){return array('data'=>array(array('event_name'=>'Purchase','event_time'=>self::order_time($o),'action_source'=>'website','event_id'=>$id,'user_data'=>self::user_data($o),'custom_data'=>array('currency'=>$o->get_currency(),'value'=>(float)$o->get_total(),'order_id'=>(string)$o->get_id(),'content_type'=>'product'))));}
    private static function delivered_payload($o,$id){$d=$o->get_date_created();$t=$d?$d->getTimestamp():time();$delivered_at=$o->get_meta('_smf_delivered_at');if($delivered_at&&is_numeric($delivered_at))$t=(int)$delivered_at;return array('data'=>array(array('event_name'=>'OrderDelivered','event_time'=>$t,'action_source'=>'website','event_id'=>$id,'user_data'=>self::user_data($o),'custom_data'=>array('currency'=>$o->get_currency(),'value'=>(float)$o->get_total(),'order_id'=>(string)$o->get_id(),'content_type'=>'product','order_status'=>'delivered'))));}
    private static function order_time($o){$d=$o->get_date_created();return $d?$d->getTimestamp():time();}
    private static function configured(){return get_option('smf_meta_enabled','no')==='yes'&&trim((string)get_option('smf_meta_pixel_id',''))!==''&&trim((string)get_option('smf_meta_access_token',''))!=='';}
    private static function user_data($o){$d=array();$email=strtolower(trim((string)$o->get_billing_email()));$phone=preg_replace('/[^0-9]/','',(string)$o->get_billing_phone());if($email)$d['em']=array(hash('sha256',$email));if($phone)$d['ph']=array(hash('sha256',$phone));$fbc=$o->get_meta('_smf_fbc');$fbp=$o->get_meta('_smf_fbp');if($fbc)$d['fbc']=sanitize_text_field($fbc);if($fbp)$d['fbp']=sanitize_text_field($fbp);return $d;}
    private static function queue_event($order_id,$name,$id,$payload){global $wpdb;$table=$wpdb->prefix.'smf_capi_queue';$now=current_time('mysql');$sql="INSERT IGNORE INTO $table (order_id,event_name,event_id,payload,attempts,status,next_attempt_at,created_at) VALUES (%d,%s,%s,%s,0,'pending',%s,%s)";return false!==$wpdb->query($wpdb->prepare($sql,absint($order_id),sanitize_text_field($name),sanitize_text_field($id),wp_json_encode($payload),$now,$now));}
    public static function process_queue(){if(!self::configured()||!self::acquire_lock())return;global $wpdb;$table=$wpdb->prefix.'smf_capi_queue';try{$stale=wp_date('Y-m-d H:i:s',current_time('timestamp')-self::LOCK_TTL,wp_timezone());$wpdb->query($wpdb->prepare("UPDATE $table SET status='pending' WHERE status='processing' AND next_attempt_at<=%s",$stale));$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table WHERE status='pending' AND next_attempt_at<=%s ORDER BY id ASC LIMIT %d",current_time('mysql'),self::BATCH_SIZE),ARRAY_A);foreach((array)$rows as $row){$claim_until=wp_date('Y-m-d H:i:s',current_time('timestamp')+self::LOCK_TTL,wp_timezone());$claimed=$wpdb->query($wpdb->prepare("UPDATE $table SET status='processing',next_attempt_at=%s WHERE id=%d AND status='pending'",$claim_until,(int)$row['id']));if($claimed!==1)continue;$payload=json_decode($row['payload'],true);if(!is_array($payload)){self::fail_row($row,'Invalid queued payload.');continue;}$result=self::post($payload);if($result['success'])$wpdb->update($table,array('status'=>'sent','sent_at'=>current_time('mysql'),'last_error'=>null,'next_attempt_at'=>current_time('mysql')),array('id'=>(int)$row['id']),array('%s','%s','%s','%s'),array('%d'));else self::fail_row($row,$result['error']);}}finally{delete_option(self::LOCK_KEY);}}
    private static function acquire_lock(){return add_option(self::LOCK_KEY,(string)time(),'','no');}
    private static function fail_row($row,$error){global $wpdb;$table=$wpdb->prefix.'smf_capi_queue';$attempts=(int)$row['attempts']+1;if($attempts>=self::MAX_ATTEMPTS){$wpdb->update($table,array('attempts'=>$attempts,'status'=>'failed','last_error'=>substr((string)$error,0,1000)),array('id'=>(int)$row['id']),array('%d','%s','%s'),array('%d'));return;}$delays=array(300,900,3600,10800);$next=wp_date('Y-m-d H:i:s',current_time('timestamp')+$delays[min($attempts-1,3)],wp_timezone());$wpdb->update($table,array('attempts'=>$attempts,'status'=>'pending','next_attempt_at'=>$next,'last_error'=>substr((string)$error,0,1000)),array('id'=>(int)$row['id']),array('%d','%s','%s','%s'),array('%d'));}
    public static function get_queue_stats(){global $wpdb;$table=$wpdb->prefix.'smf_capi_queue';$s=array('pending'=>0,'processing'=>0,'sent'=>0,'failed'=>0,'total'=>0,'last_sent'=>null,'last_error'=>null);$rows=$wpdb->get_results("SELECT status,COUNT(*) count FROM $table GROUP BY status",ARRAY_A);foreach((array)$rows as $r)if(isset($s[$r['status']]))$s[$r['status']]=(int)$r['count'];$s['total']=$s['pending']+$s['processing']+$s['sent']+$s['failed'];$s['last_sent']=$wpdb->get_var("SELECT sent_at FROM $table WHERE status='sent' ORDER BY sent_at DESC LIMIT 1");$s['last_error']=$wpdb->get_var("SELECT last_error FROM $table WHERE last_error IS NOT NULL AND last_error<>'' ORDER BY id DESC LIMIT 1");return $s;}
    public static function test_connection(){if(!current_user_can('manage_woocommerce'))wp_send_json_error(array('message'=>'Permission denied.'),403);check_ajax_referer('smf_admin','nonce');$pixel=preg_replace('/[^0-9]/','',(string)get_option('smf_meta_pixel_id',''));$token=trim((string)get_option('smf_meta_access_token',''));if(!$pixel||!$token)wp_send_json_error(array('message'=>'Add Pixel ID and access token first.'),400);$r=wp_remote_get('https://graph.facebook.com/v23.0/'.rawurlencode($pixel),array('timeout'=>15,'headers'=>array('Accept'=>'application/json','Authorization'=>'Bearer '.$token),'body'=>array('fields'=>'id,name')));if(is_wp_error($r))wp_send_json_error(array('message'=>$r->get_error_message()),502);$code=(int)wp_remote_retrieve_response_code($r);$body=json_decode(wp_remote_retrieve_body($r),true);if($code>=200&&$code<300&&!empty($body['id']))wp_send_json_success(array('message'=>'Meta connection successful.','pixel_id'=>$body['id'],'name'=>isset($body['name'])?$body['name']:''));$msg=!empty($body['error']['message'])?$body['error']['message']:'Meta returned HTTP '.$code.'.';wp_send_json_error(array('message'=>$msg),$code>=400&&$code<600?$code:502);}
    private static function post($payload){$pixel=preg_replace('/[^0-9]/','',(string)get_option('smf_meta_pixel_id',''));$token=trim((string)get_option('smf_meta_access_token',''));if(!$pixel||!$token)return array('success'=>false,'error'=>'Meta Pixel ID or access token is missing.');$r=wp_remote_post('https://graph.facebook.com/v23.0/'.rawurlencode($pixel).'/events',array('timeout'=>15,'headers'=>array('Content-Type'=>'application/json','Authorization'=>'Bearer '.$token),'body'=>wp_json_encode($payload)));if(is_wp_error($r))return array('success'=>false,'error'=>$r->get_error_message());$code=(int)wp_remote_retrieve_response_code($r);if($code>=200&&$code<300)return array('success'=>true,'error'=>'');$body=json_decode(wp_remote_retrieve_body($r),true);return array('success'=>false,'error'=>!empty($body['error']['message'])?$body['error']['message']:'Meta returned HTTP '.$code.'.');}
}
