<?php
defined('ABSPATH') || exit;

class SMF_Attribution {
    public static function empty() { return array('fbclid'=>'','utm_source'=>'','utm_medium'=>'','utm_campaign'=>'','utm_content'=>'','utm_term'=>'','utm_id'=>'','campaign_id'=>'','adset_id'=>'','ad_id'=>'','fbp'=>'','fbc'=>''); }
    public static function normalize($data) { $out=self::empty(); if(!is_array($data))return $out; foreach($out as $key=>$unused)if(isset($data[$key])&&is_scalar($data[$key]))$out[$key]=sanitize_text_field((string)$data[$key]); return $out; }
    public static function session_row($session_key){global $wpdb;if(!preg_match('/^[a-f0-9-]{36}$/',$session_key))return null;return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->prefix.'smf_tracking_sessions WHERE session_key=%s LIMIT 1',$session_key));}
    public static function first($session_key){$row=self::session_row($session_key);return $row&&!empty($row->first_touch)?self::normalize(json_decode($row->first_touch,true)):self::empty();}
    public static function last($session_key){$row=self::session_row($session_key);return $row&&!empty($row->last_touch)?self::normalize(json_decode($row->last_touch,true)):self::empty();}
    public static function touch($session_key,$attribution=array()){global $wpdb;if(!preg_match('/^[a-f0-9-]{36}$/',$session_key))return false;$current=self::session_row($session_key);$incoming=self::normalize($attribution);$first=$current&&!empty($current->first_touch)?self::normalize(json_decode($current->first_touch,true)):self::empty();$last=$current&&!empty($current->last_touch)?self::normalize(json_decode($current->last_touch,true)):self::empty();$has_new=false;foreach($incoming as $v)if($v!==''){$has_new=true;break;}if($has_new){foreach($incoming as $key=>$value)if($value!=='')$last[$key]=$value;if(!self::has_any($first))$first=$last;}$updates=array('last_seen'=>current_time('mysql'),'last_touch'=>wp_json_encode($last));if($has_new&&!self::has_any($first))$updates['first_touch']=wp_json_encode($first);return false!==$wpdb->update($wpdb->prefix.'smf_tracking_sessions',$updates,array('session_key'=>$session_key));}
    public static function create_session($data=array()){global $wpdb;$first=self::normalize($data);$key=wp_generate_uuid4();$now=current_time('mysql');$row=array('session_key'=>$key,'landing_url'=>isset($_SERVER['REQUEST_URI'])?esc_url_raw(wp_unslash($_SERVER['REQUEST_URI'])):null,'first_seen'=>$now,'last_seen'=>$now,'first_touch'=>wp_json_encode($first),'last_touch'=>wp_json_encode($first));foreach(array('fbclid','fbp','fbc','utm_source','utm_medium','utm_campaign','utm_content','utm_term','utm_id','campaign_id','adset_id','ad_id') as $field)$row[$field]=!empty($first[$field])?sanitize_text_field($first[$field]):null;$wpdb->insert($wpdb->prefix.'smf_tracking_sessions',$row);return $key;}
    private static function has_any($data){foreach(self::normalize($data) as $v)if($v!=='')return true;return false;}
}
